### ISSUE TITLE
Export individual classes

### ISSUE THREAD

**Issue by sullenel** [watery-desert/loading_animation_widget#3]
Thanks for the package. 

Could you export individual classes (`Beat`, `BouncingBall`, etc) from the lib? Asking this since it is not possible to use `const` with static methods

**Comment by watery-desert** [comment]
Why do you want to use `const`? What's the issue?

**Comment by sullenel** [comment]
Using const is a subjective topic anyway, so ignore the silly request.

**Comment by watery-desert** [comment]
Hmm. It's not subjective, making an object `const` helps to improve performance. However here using `const` won't make much difference in performance. Since animations are performance intensive. All of those individual animations are `StatefulWidget` their `build` methods are constantly called to show the animation. I would expose individual classes, but there is no benefit I found. If you see some performance issue let me know.
